### ISSUE TITLE
Help Why does it make all blocks invisible

### ISSUE THREAD

**Issue by intergrav** [MayaqqDev/Calcium#1]
Help me I am using Calcium on my Minecraft forge 1.16.5 and it makes every block invisible please help Me

**Comment by intergrav** [comment]
I forgot to mention I'm using sodium and phosphor here's proof :

![image](https://user-images.githubusercontent.com/42325132/226475353-c9693559-9b90-4183-8571-02c8f28bcbda.png)

**Comment by Shiggy-dev** [comment]
🔥 fps though can't deny that

**Comment by intergrav** [comment]
This Is Still Not Fixed please fix this MayaqqDev

**Comment by TheKodeToad** [comment]
- `git clone https://github.com/MayaqqDev/Calcium`
- `rm -rf src/main/java/dev/mayaqq/calcium/mixin`
- `rm -f src/main/resources/calcium.mixins.json`
- `sed -i '26d' src/main/resources/fabric.mod.json`
- `./gradlew build`
- `rm -f ~/.minecraft/mods/calcium-1.0.0.jar`
- `cp build/libs/calcium-1.0.0.jar ~/.minecraft/mods`

this should fix it!

**Comment by MayaqqDev** [comment]
So true
